Models/ConfigurationModel.cs
using System;
using Nop.Web.Framework.Models;
using Nop.Web.Framework.Mvc.ModelBinding;
using System.ComponentModel.DataAnnotations;

namespace Nop.Plugin.Misc.GoogleVisionProductTags.Models
{
    /// <summary>
    /// Represents plugin configuration model
    /// </summary>
    public class ConfigurationModel : BaseNopModel
    {
        [NopResourceDisplayName("Plugins.Misc.GoogleVisionProductTags.GoogleApiKey")]
        public string GoogleApiKey { get; set; }

        [NopResourceDisplayName("Plugins.Misc.GoogleVisionProductTags.MaxTagsPerImage")]
        public int MaxTagsPerImage { get; set; }

        [NopResourceDisplayName("Plugins.Misc.GoogleVisionProductTags.MinConfidenceScore")]
        [Range(0, 1)]
        public decimal MinConfidenceScore { get; set; }

        [NopResourceDisplayName("Plugins.Misc.GoogleVisionProductTags.MinTopicality")]
        [Range(0, 1)]
        public decimal MinTopicality { get; set; }
    }
}

Components/GenerateAllProductTagsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Nop.Web.Framework.Components;
using System;

namespace Nop.Plugin.Misc.GoogleVisionProductTags.Components
{
    [ViewComponent(Name = "GenerateAllProductTags")]
    public class GenerateAllProductTagsViewComponent : NopViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View("~/Plugins/Misc.GoogleVisionProductTags/Views/TagsGeneration/GenerateAllProductTags.cshtml");
        }
    }
}

Controllers/GoogleVisionProductTagsController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;
using Nop.Services.Configuration;
using Nop.Services.Security;
using Nop.Services.Localization;
using Nop.Services.Messages;
using Nop.Plugin.Misc.GoogleVisionProductTags.Models;
using Nop.Plugin.Misc.GoogleVisionProductTags.Services;

namespace Nop.Plugin.Misc.GoogleVisionProductTags.Controllers
{
    public class GoogleVisionProductTagsController : BasePluginController
    {
        #region Fields

        private readonly GoogleVisionProductTagsSettings _googleVisionProductTagsSettings;
        private readonly IPermissionService _permissionService;
        private readonly ISettingService _settingService;
        private readonly ILocalizationService _localizationService;
        private readonly INotificationService _notificationService;
        private readonly IGoogleVisionProductTagsGenerator _googleVisionProductTagsGenerator;

        #endregion

        #region Ctor

        public GoogleVisionProductTagsController(GoogleVisionProductTagsSettings googleVisionProductTagsSettings,
            IPermissionService permissionService,
            ISettingService settingService,
            ILocalizationService localizationService,
            INotificationService notificationService,
            IGoogleVisionProductTagsGenerator googleVisionProductTagsGenerator)
        {
            _googleVisionProductTagsSettings = googleVisionProductTagsSettings;
            _permissionService = permissionService;
            _settingService = settingService;
            _localizationService = localizationService;
            _notificationService = notificationService;
            _googleVisionProductTagsGenerator = googleVisionProductTagsGenerator;
        }

        #endregion

        #region Methods

        [AuthorizeAdmin]
        [Area(AreaNames.Admin)]
        public IActionResult Configure()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageProducts))
                return AccessDeniedView();

            var model = new ConfigurationModel()
            {
                GoogleApiKey = _googleVisionProductTagsSettings.GoogleApiKey,
                MaxTagsPerImage = _googleVisionProductTagsSettings.MaxTagsPerImage,
                MinConfidenceScore = _googleVisionProductTagsSettings.MinConfidenceScore,
                MinTopicality = _googleVisionProductTagsSettings.MinTopicality
            };

            return View("~/Plugins/Misc.GoogleVisionProductTags/Views/Configure.cshtml", model);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        [AuthorizeAdmin]
        [Area(AreaNames.Admin)]
        public IActionResult Configure(ConfigurationModel model)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageProducts))
                return AccessDeniedView();

            if (!ModelState.IsValid)
                return Configure();

            // save settings
            _googleVisionProductTagsSettings.GoogleApiKey = model.GoogleApiKey;
            _googleVisionProductTagsSettings.MaxTagsPerImage = model.MaxTagsPerImage;
            _googleVisionProductTagsSettings.MinConfidenceScore = model.MinConfidenceScore;
            _googleVisionProductTagsSettings.MinTopicality = model.MinTopicality;
            _settingService.SaveSetting(_googleVisionProductTagsSettings);

            _notificationService.SuccessNotification(_localizationService.GetResource("Admin.Plugins.Saved"));

            return Configure();
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        [AuthorizeAdmin]
        [Area(AreaNames.Admin)]
        public async Task<IActionResult> GenerateTagsForAllProducts()
        {
            try
            {
                await _googleVisionProductTagsGenerator.GenerateTagsForAllProducts();
                _notificationService.SuccessNotification(_localizationService.GetResource("Plugins.Misc.GoogleVisionProductTags.TagsGenerated"));
            } catch (Exception exc)
            {
                _notificationService.ErrorNotification(exc);
            }
            return RedirectToAction("ProductTags", "Product");
        }

        #endregion
    }
}

Views/Configure.cshtml
@model Nop.Plugin.Misc.GoogleVisionProductTags.Models.ConfigurationModel

@inject Nop.Core.IWebHelper webHelper

@{
    Layout = "_ConfigurePlugin";
}

<form asp-controller="GoogleVisionProductTags" asp-action="Configure" method="post">
    <div class="panel-group">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-label asp-for="GoogleApiKey" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="GoogleApiKey" asp-required="true" asp-value="@Model.GoogleApiKey" />
                        <span asp-validation-for="GoogleApiKey"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-label asp-for="MaxTagsPerImage" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="MaxTagsPerImage" asp-required="true" asp-value="@Model.MaxTagsPerImage" />
                        <span asp-validation-for="MaxTagsPerImage"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-label asp-for="MinConfidenceScore" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="MinConfidenceScore" asp-required="true" asp-value="@Model.MinConfidenceScore" />
                        <span asp-validation-for="MinConfidenceScore"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-label asp-for="MinTopicality" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="MinTopicality" asp-required="true" asp-value="@Model.MinTopicality" />
                        <span asp-validation-for="MinTopicality"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-9 col-md-offset-3">
                        <input type="submit" name="save" class="btn bg-primary" value="@T("Admin.Common.Save")" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

Views/TagsGeneration/GenerateAllProductTags.cshtml
@inject Nop.Core.IWebHelper webHelper

<form asp-controller="GoogleVisionProductTags" asp-action="Configure" method="post">
    <button type="button" name="importexcel" class="btn bg-blue" data-toggle="modal" data-target="#googlevision-product-tags-confirmation-modal">
        <i class="fa fa-google"></i>
        @T("Plugins.Misc.GoogleVisionProductTags.GenerateProductTags")
    </button>
</form>
<script>
    $(document).ready(function () {
        $('body').append(`@Html.Raw((await Html.PartialAsync("~/Plugins/Misc.GoogleVisionProductTags/Views/TagsGeneration/_ConfirmationModal.cshtml")).ToHtmlString())`);
        $('#googlevision-product-tags-confirmation-modal-cancel-button').bind('click', function () {
            $('#googlevision-product-tags-confirmation-modal').toggle('modal');
        });
    });
</script>

Views/TagsGeneration/_ConfirmationModal.cshtml
<div id="googlevision-product-tags-confirmation-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="googlevision-product-tags-confirmation-modal-title">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <form asp-controller="GoogleVisionProductTags" asp-action="GenerateTagsForAllProducts" method="post">
                <div class="form-horizontal">
                    <div class="modal-body">
                        <ul class="common-list">
                            <li>
                                <em>@T("Plugins.Misc.GoogleVisionProductTags.GenerateAllProductTagsWarning")</em>
                            </li>
                        </ul>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary pull-right">
                            @T("Plugins.Misc.GoogleVisionProductTags.GenerateProductTags")
                        </button>
                        <span class="btn btn-default pull-right margin-r-5" data-dismiss="modal">@T("Plugins.Misc.GoogleVisionProductTags.Cancel")</span>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>